### ISSUE TITLE
Handle values containing new-line, line-feed and comma characters

### ISSUE THREAD

**Issue by sudiptochoudhury** [sguha-work/csv-array#1]
How do you handle values containing new-line, line-feed and comma characters?

**Comment by sguha-work** [comment]
Will get back to you as soon as possible sudipto da, having a very busy day at
office.

**Comment by sguha-work** [comment]
Actually I didn't handle them at all. Reading the file line wise and splitting the line based on comma. Now if a value holds comma then according to valid CSV file they should be wrapped up under double quote. So in time of splitting the line i only considering the double quotes and that's produce d result. There is a bug in the present version 0.0.14 which will be fixed and published as 0.0.15 within tomorrow. I like to say that d package need a lot more checking than i did. It will be very helpful if u provide some CSV files good enough for testing this parsing program.

**Comment by sudiptochoudhury** [comment]
I don't have sample CSVs as of now, but can recall some of the roadblocks that I faced and you might face too:
- If values contain newline/line feed and you are reading line wise - your code will pick broken values.

For example:

id, Name, Address
01, Sudi, "99 X Road
Kol WB"
02, Guha, "What ever"

holds 2 records and a header
- Double quotes may be present as part of a value and in csv these double quotes are  represented by a pair of double quotes. In case you do not have a check for this and split using double quotes you might end up getting a number of extra blank values in some use-cases like:

01, """Hi"",he said,""are you hungry for more?"",","2015-04-23"

Has 3 values in which the middle one is:

"Hi",he said,"are you hungry for more?",

There are a few more which I will recollect and pass on to you.

Great going so far. Keep up the good work and will try to give as much inputs as I can.

**Comment by sguha-work** [comment]
Got your point sudipto da.... thanks a lot for pointing out... will do something about those also very soon..
